my.text<-"time.ants<-0
           at.anthill<-rep(TRUE,3)
           done.all<-0
           done<-rep(0,3)
           food<-c(rpois(8,lambda=10),0,0)
           site<-c(10,10,10)
           carry<-c(0,0,0)
           visited.sites<-list(numeric(0),numeric(0),numeric(0))
           total.visited.sites<-rep(0,3)"
 writeLines(my.text,con="r-code/Ant-Simulation/initialize.txt")
